import { precacheAndRoute, cleanupOutdatedCaches, matchPrecache } from 'workbox-precaching';
import { registerRoute, setCatchHandler } from 'workbox-routing';
import { CacheFirst, NetworkFirst, NetworkOnly } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { clientsClaim } from 'workbox-core';

// Content-hashed app shell + assets are injected here by vite-plugin-pwa.
precacheAndRoute(self.__WB_MANIFEST, { directoryIndex: null });

self.skipWaiting();
clientsClaim();

// Remove caches generated by the old hand-rolled service worker.
cleanupOutdatedCaches();
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames
          .filter((name) => name.startsWith('royalemy-'))
          .map((name) => caches.delete(name))
      )
    )
  );
});

// ==================== API ROUTES ====================
// The API is cross-origin (VITE_API_URL points to a different host), so these
// routes match by url.pathname regardless of origin.

// /api/cards changes very rarely.
registerRoute(
  ({ url }) => url.pathname === '/api/cards',
  new CacheFirst({
    cacheName: 'api-cards',
    plugins: [new ExpirationPlugin({ maxEntries: 1, maxAgeSeconds: 60 * 60 * 24 })],
  })
);

// /api/locations/* and /api/meta-decks are dynamic but cacheable for offline.
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/locations') || url.pathname === '/api/meta-decks',
  new NetworkFirst({
    cacheName: 'api-dynamic',
    plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 })],
  })
);

// All other API calls are never cached.
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkOnly()
);

// ==================== FONTS ====================

registerRoute(
  ({ url }) => url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'fonts',
    plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 365 })],
  })
);

// ==================== IMAGES ====================

registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  })
);

// ==================== JS/CSS/DOCUMENTS ====================

registerRoute(
  ({ request }) => ['script', 'style', 'document'].includes(request.destination),
  new NetworkFirst({
    cacheName: 'assets',
    plugins: [new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 * 7 })],
  })
);

// ==================== NAVIGATION / OFFLINE FALLBACK ====================

registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages',
    plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 })],
  })
);

setCatchHandler(async ({ event }) => {
  if (event.request.mode === 'navigate') {
    const fallback = await matchPrecache('/offline.html');
    if (fallback) return fallback;
  }
  return Response.error();
});

// ==================== UPDATE PROMPT MESSAGE ====================

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// ==================== PUSH NOTIFICATIONS (verbatim from legacy sw.js) ====================

self.addEventListener('push', (event) => {
  if (!event.data) return;
  try {
    const data = event.data.json();
    const title = data.title || 'RoyaleMY Update';
    const scope = data.scope || 'global';
    const scopeLabel = scope === 'tournament' ? 'View Tournament' : 'Open RoyaleMY';
    const options = {
      body: data.body || 'You have a new site update.',
      icon: data.icon || '/royalemy.png',
      badge: '/icons/icon-192x192.png',
      tag: data.tag || 'royalemy-update',
      requireInteraction: false,
      data: {
        tournamentId: data.tournamentId,
        url: data.url || '/',
        scope
      },
      actions: [
        { action: 'open', title: scopeLabel },
        { action: 'close', title: 'Dismiss' }
      ]
    };
    event.waitUntil(self.registration.showNotification(title, options));
  } catch (e) {
    console.error('[SW] Failed to handle push:', e);
  }
});

// ==================== NOTIFICATION CLICK HANDLER (verbatim from legacy sw.js) ====================

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  if (event.action === 'close') return;
  const url = event.notification.data?.url || '/';
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(url);
      }
    })
  );
});
