name: Deploy to JustRunMyApp

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to JustRunMyApp registry
        run: |
          echo "${{ secrets.JRNM_PASSWORD }}" | docker login \
            -u "${{ secrets.JRNM_USERNAME }}" \
            --password-stdin \
            jdr-z84fc52po9.justrunmy.app

      - name: Create dynamic tag
        id: meta
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          IMAGE="jdr-z84fc52po9.justrunmy.app/z84fc52po9"

          docker build -t $IMAGE:latest .
          docker tag $IMAGE:latest $IMAGE:${{ steps.meta.outputs.tag }}

      - name: Push Docker images
        run: |
          IMAGE="jdr-z84fc52po9.justrunmy.app/z84fc52po9"

          docker push $IMAGE:latest
          docker push $IMAGE:${{ steps.meta.outputs.tag }}
